### ISSUE TITLE
The model crash due to write calls for new wave related fields

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/schism#4]
@josephzhang8 Thanks for adding new wave related variables to output but when I run the code, the model is crashing and there is a `2: ABORT: writeout_nc: irec<=0` message in the `outputs/fatal.error` file. If I comment out new whiteout_nc calls from `SCHISM/src/Hydro/misc_subs.F90`, then code works. I just wonder if you test this in your end. Maybe I need to add something to `param.nml` that I don't know.

**Comment by josephzhang8** [comment]
Will test after OSM. Thx for testing; there may be issues with my changes.

**Comment by uturuncoglu** [comment]
@josephzhang8 JFYI, this version of code is also producing error like `compute_wave_force_lon: NaN- see nonfatal`. So, there might be some bug in that part of the code. Maybe it is failing since I remove write_nc. Anyway, I am not sure where is the issue but `c5cd94081af30c57497e03bd303296380b4cd9dc` hash is fine. This is just after my build update PR.

**Comment by uturuncoglu** [comment]
@josephzhang8 @platipodium As I understand (please correct me if I am wrong), the `SCHISM_StateImportWaveTensor` routine is getting wave related import fields and passing them to `compute_wave_force_lon` to calculate some internal variables (and writing stress components - recently implemented). But it seems that this is not following the convention that is used in `SCHISM_StateUpdate` and still assumes node based mesh. Since we have no element based mesh I think this needs to be updated like `SCHISM_StateUpdate`. I am not sure at this point this is the root cause of the issue or not but at least it seems there is a bug in here. I also look at `writeout_nc` call and print out `it_main`, `ifile`, `ihfskip` and `nspool` and it returns `0`, `1`, `432` and `9`. So, the irec gets 0 in this case and model aborts and it expected. I am not sure what is wrong in here but maybe this is failing since it is called by the cap but not by the model. The `compute_wave_force_lon` call is in the model side but it is only used by the NUOPC cap. Anyway, maybe the logic in here needs to be changed to be able to write those variables coming from wave component.

**Comment by platipodium** [comment]
@uturuncoglu thanks for looking into this. The `compute_wave_force_lon` call from the cap ` SCHISM_StateImportWaveTensor()` was a hot fix, has not been tested well, so it is likely that it is buggy.   If you have a suggestion on how to change this, I'd appreciate your input!

**Comment by uturuncoglu** [comment]
@platipodium @josephzhang8 I think `compute_wave_force_lon` call needs to be moved to the cap since it is not used by the model itself. Only, NUOPC cap needs it. Then, I think `writeout_nc` calls need to be move to the model. I am not sure about the right place at this point but I think this separation will make the code more clean.

**Comment by uturuncoglu** [comment]
Why we are calling `writeout_nc` from the cap `SCHISM-ESMF/src/schism/schism_esmf_cap.F90`. This is supposed to be model internal call like in its run routine. But I think this is because of split between cap and model. In fact that the init, run and finalize needs to be implemented in the model level and cap just need to call them. In the uncoupled configuration the main program will call them in an order. Anyway, I think we could not restructure everything in here but at least I need to fix the issue related writing the wave related fields. I'll update about it.

**Comment by platipodium** [comment]
> @platipodium @josephzhang8 I think `compute_wave_force_lon` call needs to be moved to the cap since it is not used by the model itself. 

As `compute_wave_force_lon` is used by either NUOPC or ESMF cap, it should be moved to the shared `schism_esmf_util.F90`

**Comment by platipodium** [comment]
> Then, I think `writeout_nc` calls need to be move to the model. I am not sure about the right place at this point but I think this separation will make the code more clean.

It seems these calls were added by CWB for the coupling with PDAF (which we have in a non-NUOPC coupling).  As it is only in the non-nuopc cap I think we should disregard this for now.

**Comment by uturuncoglu** [comment]
@platipodium @josephzhang8 Okay. I think I solved this too. It is not the best way but I'll create a draft PR in the model side for too since I have minor modification in there. I am also removing `writeout_nc` calls from `compute_wave_force_lon`since I move them to `schism_step`.

**Comment by uturuncoglu** [comment]
@platipodium @josephzhang8 Here is the model level draft PR - https://github.com/schism-dev/schism/pull/126. Please check initially and let me know what you think.
@pvelissariou1 I am plaining to point this branch in the ufs-coastal and then once we update the test case and we could run the all schism related cases and check the results carefully to be sure that they are working as expected.
@janahaddad JFYI, i transfer the reproducibility issue to schism-esmf since it is the right place  - https://github.com/oceanmodeling/schism-esmf/issues/2

**Comment by josephzhang8** [comment]
Thx @uturuncoglu @platipodium for working on this! As @platipodium mentioned we were not sure about the right way to implement the routine call inside the cap so it was a temp fix. It'd be great if we'd integrate it into the cap as @uturuncoglu suggested.

I'm ok with the PR and will only add a few conditionals for the allocate (to conserve memory). Thx!

**Comment by josephzhang8** [comment]
@uturuncoglu I can accept this PR and merge; just wondering if you want to go ahead and implement the clean separation idea you mentioned before the merge, or we can work on that later?

The problem as I recalled, was that the cap would require many arrays from schism_glbl and schism_msgp (for ghost exchange). This'd become more complex when we move to 3D vortex formulation. Any suggestions? Thx.

**Comment by uturuncoglu** [comment]
The PR that seems fixed the issue is still open https://github.com/schism-dev/schism/pull/126.

**Comment by uturuncoglu** [comment]
@josephzhang8 Sorry for late response. At this point, I restructure the cap to make it more flexible and clean. I think we could try to fix other issues later. I think there is no any issue to access `schism_glbl` and `schism_msgp` unless we are trying to reach some internal data structure of the model. If the variable defined in there totally uses by the NUOPC or ESMF caps and then it would be nice to move those to cap and remove from the model. The cap needs to be self-contained. BTW, I am not sure why we have two cap ESMF vs. NUOPC in the SCHSIM side. Is it due to historical reasons or you need to support some other modeling system or cases that does not allow to use NUOPC cap?

**Comment by josephzhang8** [comment]
Thx @uturuncoglu for the fixes in the cap. @danishyo has tested it with FV3 and it worked!
@platipodium can answer the 2 caps question.

As of now, subroutine compute_wave_force_lon is still inside SCHISM (misc_subs). I agree that this really should belong to cap, but I don't know how to do that b/c it requires many variables (like geometry) from SCHISM. I hope we can get this settled before we move to 3D vortex coupling.

**Comment by platipodium** [comment]
@uturuncoglu please move compute_wave_force_lon to the cap.  I would suggest a separate file and module for this in the cap in `./src/schism/`

**Comment by uturuncoglu** [comment]
The fix is merged - https://github.com/schism-dev/schism/pull/126. I am closing this.

**Comment by uturuncoglu** [comment]
I'll update master branch and point in ufs-coastal.
