### ISSUE TITLE
Create real atm fields for SCHISM Shinnecock domain RTs 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/schism#5]
Needed to build realistic wind fields case for UFS-CAT tutorial on March 1. These new RT configs will then be tested by @yunfangsun, to replace: coastal_ike_shinnecock_atm2sch_intel, coastal_ike_shinnecock_atm2ww3_intel, coastal_ike_shinnecock_atm2sch2ww3_intel (when Ufuk confirms it's ready)

Possibly use the previous test case for Sandy on Shinnecock domain

**Comment by pvelissariou1** [comment]
@yunfangsun , Yunfang I have put the Sandy Shinnecock data in "hera" at: /scratch2/STI/coastal_temp/save/Panagiotis.Velissariou/shinecock_atm. Could you please plot the 2D wind speeds and the Shinnecock domain on top as well as the path of the hurricane Sandy (with the 35 kn contour)? I will update the test cases for SCHISM after that.

**Comment by yunfangsun** [comment]
@pvelissariou1 

The Sandy path and computation domain is as follows:
![sandy_mesh](https://github.com/oceanmodeling/schism/assets/122925778/e1fab976-ea64-4e28-97f2-21aa782a5574)
![sandy](https://github.com/oceanmodeling/schism/assets/122925778/61669956-4f77-4e20-a702-2bd6326735f8)

Hera is on maintenance today 8:00-16:00, therefore, I can't see your atm forcing, and I don't have Python script to plot the vector field.

**Comment by pvelissariou1** [comment]
@yunfangsun Thank you. So I will set the test cases for Sandy, as in SCHISM+PAHM cases.

**Comment by pvelissariou1** [comment]
@yunfangsun Hera is up, could you please get the atm fields and see if you can plot the wind maps?

**Comment by pvelissariou1** [comment]
@yunfangsun The only CO-OPS station I found is: 8512354 SHINNECOCK INLET OPEN COAST, NY but contains only tide elevations

**Comment by janahaddad** [comment]
@pvelissariou1 @yunfangsun How about using the Montauk, NY station:
https://tidesandcurrents.noaa.gov/waterlevels.html?id=8510560 

It's in the domain, not too far from the inlet

**Comment by janahaddad** [comment]
@pvelissariou1 @yunfangsun -- nope, I'm wrong, Montauk is not in the domain!

**Comment by pvelissariou1** [comment]
@janahaddad It is outside the computational domain of Shinnecock inlet
 I believe.

**Comment by janahaddad** [comment]
There is apparently a USGS station in the bay: https://waterdata.usgs.gov/monitoring-location/01304746/#parameterCode=62619&period=P7D&showMedian=true 

WL data is available above NAVD88 starting Oct 2016.

**Comment by pvelissariou1** [comment]
@janahaddad Thank you Jana for checking on this. I checked this station, but has no data for 2012 (Sandy). I might check the global database, but I dont't think we can find anything. @yunfangsun let's see if we can have those 2D maps for Shinnecock. We might do comparison of the tidal water levels only. Anyway, I am working on the test case so Ufuk and I can test ...

**Comment by yunfangsun** [comment]
Hi @pvelissariou1 ,

I have plotted the atmospheric wind field from the forcing file you generated, however, the file is larger than 10MB, which could not be uploaded on Github, then I put it in /scratch2/STI/coastal/Yunfang.Sun/Sandy/wind_vector_field.gif on Hera, please check it there. Thank you.

**Comment by pvelissariou1** [comment]
@yunfangsun Thank you. I was thinking contour maps not vector fields. Also it might be helpful to include the mesh domain over the contour maps as well.

**Comment by yunfangsun** [comment]
Hi @pvelissariou1 , I have plotted the field, with the color showing the wind speed, and also included the mesh domain, please find it in /scratch2/STI/coastal/Yunfang.Sun/Sandy/wind_vector_field_colored_by_speed_domain.gif on Hera, and I will download the station 8512354 to do the plot. Thank you.

**Comment by pvelissariou1** [comment]
@yunfangsun Is it possible to fix the colorbar range, say 0 - 20 m/s, so we can clearly see what is going on from frame to frame?

**Comment by yunfangsun** [comment]
@pvelissariou1 ok, I will do it

**Comment by yunfangsun** [comment]
Hi @pvelissariou1 

I have fixed the colorbar and changed the colormap, please take a look at /scratch2/STI/coastal/Yunfang.Sun/Sandy/wind_vector_field_colored_by_speed_fixed_colorbar.gif on Hera

**Comment by pvelissariou1** [comment]
@yunfangsun It looks much better, thank you. Is it possible to also do a contour map, without the vector field?

**Comment by yunfangsun** [comment]
@pvelissariou1 , ok, I will add a contour map

**Comment by yunfangsun** [comment]
Hi @pvelissariou1 ,

The contour map of surface forcing is ready at /scratch2/STI/coastal/Yunfang.Sun/Sandy/wind_speed_contour_map_corrected.gif

**Comment by pvelissariou1** [comment]
@yunfangsun Thank you very much. It looks good.
