### ISSUE TITLE
UFS Coastal atm2sch is failing with head of master

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/schism#7]
The UFS coastal model is failing with current version develop (cfb58a52b7109bb35dd5e1f4ecebd68f1dd08cb6) on authoritative repository and giving error like following

```
3:    0: ABORT: INIT: nbins_veg_vert<=0
4:    1: ABORT: INIT: nbins_veg_vert<=0
5:    2: ABORT: INIT: nbins_veg_vert<=0
```

**Comment by uturuncoglu** [comment]
As a part of request from @pvelissariou1 I tried to sync the SCHSIM under UFS coastal but test is failing with the error that can be found in the description. @josephzhang8 Any idea? We might need to update the configuration but not sure.

**Comment by uturuncoglu** [comment]
It seems it is triggered by `SCHISM/src/Hydro/schism_init.F90`.

**Comment by josephzhang8** [comment]
@uturuncoglu it's a simple fix. Just add the following line to the CORE section of param.nml:

nbins_veg_vert = 1

**Comment by uturuncoglu** [comment]
@josephzhang8 Thanks. Testing now. BTW, is this a new option introduced recently?

**Comment by josephzhang8** [comment]
Yes I added the new option to allow for more realistic vegetation.

**Comment by uturuncoglu** [comment]
@josephzhang8 I added option to core section,

```
&CORE
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! Core (mandatory) parameters; no defaults
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
! Pre-processing option. Useful for checking grid violations.
  ipre = 0 !Pre-processor flag (1: on; 0: off)

! Baroclinic/barotropic option. If ibc=0 (baroclinic model), ibtp is not used.
  ibc = 1 !Baroclinic option
  ibtp = 0

  rnday = 20. !total run time in days
  dt = 200. !Time step in sec

! Grid for WWM (USE_WWM)
  msc2 = 24     !same as msc in .nml ... for consitency check between SCHISM and WWM
  mdc2 = 30     !same as mdc in .nml

! Define # of tracers in tracer modules (if enabled)
  ntracer_gen = 2 !user defined module (USE_GEN)
  ntracer_age = 4 !age calculation (USE_AGE). Must be =2*N where N is # of age tracers
  sed_class = 5 !SED3D (USE_SED)
  eco_class = 27 !EcoSim (USE_ECO): must be between [25,60]

! Global output controls
  nspool = 9 !output step spool
  ihfskip = 432 !stack spool; every ihfskip steps will be put into 1_*, 2_*, etc...

  nbins_veg_vert = 1
/
```

but it is complaining about new option,

```
3: forrtl: severe (19): invalid reference to variable in NAMELIST input, unit 15, file /work2/noaa/stmp/tufuk/stmp/tufuk/FV3_RT/rt_1869133/coastal_ike_shinnecock_atm2sch_intel/.//param.nml, line 509, position 8
3: Image              PC                Routine            Line        Source
3: fv3.exe            0000000001FE1D8D  Unknown               Unknown  Unknown
3: fv3.exe            0000000001D8FE7B  schism_init_              514  schism_init.F90
3: fv3.exe            0000000001D2DA7D  schism_nuopc_cap_         345  schism_nuopc_cap.F90
```

**Comment by josephzhang8** [comment]
Can u show me line line 509 of param.nml?

I cannot read your dir on HERC

**Comment by uturuncoglu** [comment]
I think, the new parameter fixed one issue and now the error is coming from OPT section of the `param.nml`. Is there any change in that section? Like renaming existing parameter or introducing new one or removing. BTW, we have `isav = 0` in line 509.

**Comment by josephzhang8** [comment]
Ah ... just remove that line or change isav to iveg

**Comment by josephzhang8** [comment]
It's part of recent overhaul on veg module.

**Comment by uturuncoglu** [comment]
Okay. Let me try to rename as `iveg` and run the test again.

**Comment by uturuncoglu** [comment]
@josephzhang8 Okay. That solved the issue. Thanks for your help. I will also run ww3 test and also with gnu to be sure.

@pvelissariou1 @yunfangsun @janahaddad I adjusted the `/work2/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20240501/SCHISM/Ike/atm2sch2wav/param.nml` and also `/work2/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20240501/SCHISM/Ike/atm2sch/param.nml` files according to changes in the model side. We need to sync those changes to other platforms. BTW, I think input directories need to be cleaned since I am seeing `Florence/` and      `Sandy/` directories under `SCHISM` model but we have no any tests for those. Since we are already testing infrastructure with fake Ike configuration, I think it would be better to remove those folders. Let me know what you think?

**Comment by uturuncoglu** [comment]
@pvelissariou1 @yunfangsun JFYI, I have just updated SCHISM in our ufs-weather-model fork.

**Comment by yunfangsun** [comment]
@uturuncoglu 
Thank you for letting me know, I will try to test the RT from my end by using the folder of /work2/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20240501/ on Hercules.

**Comment by uturuncoglu** [comment]
@yunfangsun Let me know if you have any issue with this test. It seems it is working on Hercules after I updated the input namelist file. So, I could close this ticket.

**Comment by uturuncoglu** [comment]
@yunfangsun I just wonder if you could test this. I am plaining to close this issue.

**Comment by yunfangsun** [comment]
Hi @uturuncoglu 

I have tested the case on Hercules, `/work2/noaa/nosofs/yunfangs/stmp/yunfangs/FV3_RT/rt_3974259/coastal_ike_shinnecock_atm2sch_intel`

Please close the issue.

**Comment by uturuncoglu** [comment]
@yunfangsun Thanks.
