### ISSUE TITLE
Aquire SCHISM-3D test cases 

### ISSUE THREAD

**Issue by janahaddad** [oceanmodeling/schism#8]
Need 2-3 3D SCHISM test cases for the UFS-Coastal test suite

from UFS-Coastal WW3 tag-up on 4/1/2024 @josephzhang8 will help point us in the right direction

**Comment by uturuncoglu** [comment]
@janahaddad I transferred this issue to right place.

**Comment by uturuncoglu** [comment]
@janahaddad I am closing this since there are lots of issues related with SCHSIM+WW3 coupling. We will keep continue to use https://github.com/oceanmodeling/WW3/issues/11
